#!/bin/bash

if [ "$(whoami)" != "root" ]; then
	echo "This script needs to be run with sudo. Exiting now."
	exit 1
fi

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
echo "This script is for devices that need the XOrg Video Dummy Driver to show up properly in VNC."
echo "If the script has already run, instead of setting it up, it will uninstall the dummy driver and remove the conf file."

read -p "Do you wish to run this script? (y/n)" runscript
if [ "$runscript" != "y" ]
then
	echo "Quitting the script."
	exit
fi

if [ -e "/etc/X11/xorg.conf.d/10-videodummy.conf" ]
then
		read -p "The script was already run.  Do you wish to uninstall? (y/n)" uninstall
		if [ "$uninstall" == "y" ]
		then
			echo "Removing the dummy driver and the conf file."
			sudo apt -y remove xserver-xorg-video-dummy
			sudo rm /etc/X11/xorg.conf.d/10-videodummy.conf
		fi
		echo "Script Execution Complete.  The Video Dummy Driver is removed.  You should restart your computer."
		exit
fi


# This will install the Video Dummy Driver
sudo apt -y install xserver-xorg-video-dummy

# This will create the configuration file needed to support the dummy driver.
##################
sudo --preserve-env bash -c 'cat > /etc/X11/xorg.conf.d/10-videodummy.conf' <<- EOF
Section "Monitor"
    Identifier "Monitor0"
    HorizSync 22 - 83
    VertRefresh 50 - 76
    Modeline "1440x900" 106.47 1440 1520 1672 1904 900 901 904 932 -HSync +Vsync
    Modeline "1920x1080" 172.80 1920 2040 2248 2576 1080 1081 1084 1118 -HSync +Vsync
EndSection

Section "Device"
    Identifier "Card0"
    Option "NoDDC" "true"
    Option "IgnoreEDID" "true"
    Driver "dummy"
    VideoRam 256000
EndSection

Section "Screen"
    DefaultDepth 24
    Identifier "Screen0"
    Device "Card0"
    Monitor "Monitor0"
    SubSection "Display"
        Depth 24
        Modes "1440x900" "1920x1080"
    EndSubSection
EndSection
EOF
##################

echo "Script Execution Complete.  The Video Dummy Driver is set up.  You should restart your computer and log in via VNC."
