#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

export USERHOME=$(sudo -u $SUDO_USER -H bash -c 'echo $HOME')

if [ "$(whoami)" != "root" ]; then
	echo "This script needs to be run with sudo. Exiting now."
	exit 1
fi

# This will make sure that network manager can manage whether the ethernet connection is on or off.
echo "Setting up Ethernet for both DHCP and link-local"
if [ -n "$(grep 'managed=false' /etc/NetworkManager/NetworkManager.conf)" ]
then
	sed -i "s/managed=false/managed=true/g" /etc/NetworkManager/NetworkManager.conf
fi

nmcli connection add type ethernet ifname enP3p49s0 con-name "Ethernet" autoconnect yes
nmcli connection modify "Ethernet" connection.autoconnect-priority 2
nmcli connection modify "Ethernet" ipv4.dhcp-timeout 5
nmcli connection modify "Ethernet" ipv4.may-fail no
nmcli connection modify "Ethernet" connection.autoconnect-retries 2
nmcli connection modify "Ethernet" connection.auth-retries 2

nmcli connection add type ethernet ifname enP3p49s0 con-name "Link-Local" autoconnect yes ip4 10.0.0.60/24
nmcli connection modify "Link-Local" connection.autoconnect-priority 1


echo "Turning off Wi-Fi Power Management"
##################
sudo --preserve-env bash -c 'cat > /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf' << EOF
[connection]
wifi.powersave = 2
EOF
##################


echo "Setting up Wi-Fi Hotspot"
nmcli connection add type wifi ifname '*' con-name "HotSpot" autoconnect yes ssid "OPi5 Max"
nmcli connection modify "HotSpot" 802-11-wireless.mode ap 802-11-wireless.band a ipv4.method shared
nmcli connection modify "HotSpot" connection.autoconnect-priority -5

##################
sudo --preserve-env bash -c 'cat > /etc/NetworkManager/conf.d/wifi-enable-autohotspot.conf' << EOF
[connection-wifi]
match-device=interface-name:wlan0
ipv4.dhcp-timeout=30
ipv4.may-fail=no
connection.auth-retries=2
connection.autoconnect-retries=2
EOF
##################


# This will make sure /etc/network/interfaces does not interfere
##################
sudo --preserve-env bash -c 'cat > /etc/network/interfaces' << EOF
# interfaces(5) file used by ifup(8) and ifdown(8)
# Include files from /etc/network/interfaces.d:
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback
EOF
##################


echo "Disabling Energy Efficient Ethernet"
##################
sudo --preserve-env bash -c 'cat > /etc/systemd/system/disable-eee.service' << EOF
[Unit]
Description=Disable Energy Efficient Ethernet
After=network.target

[Service]
Type=oneshot
ExecStart=/sbin/ethtool --set-eee enP3p49s0 eee off

[Install]
WantedBy=multi-user.target
EOF
##################

sudo systemctl enable disable-eee.service
sudo systemctl start disable-eee.service


# Uncomment next lines to install realtek RTL8156 (r8152) USB 2.5G ethernet driver 
#sudo add-apt-repository ppa:awesometic/ppa -y
#sudo apt -y install realtek-r8152-dkms
